### ISSUE TITLE
Heading to bed.

### ISSUE THREAD

**Issue by palixeb** [palixeb/palixeb.github.io#3]
Thanks for the help. I still have had no luck on getting the header image (MM23.jpg) to show up on the page. I am clueless on what to do. 

Any idea as to why it works on localhost:4000 but not on github pages?

Thanks and good night.

**Comment by mvaneijgen** [comment]
Several commits later and some cursing at my screen, but it works! Im not sure what the problem was. The only problem I could find was that the error was about a `.jpg` image and all your images where `.JPG`. Changing the extension didn't re-uploaded them, so I deleted them an re uploaded them and this worked. 

Only thing is your images are REALY large they should be round `200kb` and they are around the `1,5mb`.

**Comment by palixeb** [comment]
HOLY SHIT!!!! Thank you soooooo much!

**Comment by palixeb** [comment]
Thanks for the heads up on the images! I'll resize them! 

Once again thanks!

**Comment by mvaneijgen** [comment]
No problem, good luck with the rest of building the site.

**Comment by palixeb** [comment]
Hey,

I just wanted to say thanks for your help, again. The site is "done",
albeit far from pretty, so I decided share it while I clean up the code and
make it more efficient with Liquid.

www.mannymarx.com

I was wondering if you could explain to me the magic you did with jekyll
serve --watch --config _config.yml,_config-dev-.yml.

I understand it up until --watch and then I get lost. Especially with
the _config-dev-.yml.

Thanks

Also, if you know of anyone in need of music /sounds please send them my
way!

On Sat, Nov 7, 2015 at 3:40 AM, Mitchel van Eijgen <notifications@github.com

> wrote:
> 
> No problem, good luck with the rest of building the site.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/palixeb/palixeb.github.io/issues/3#issuecomment-154497165
> .

## 

Phill Bennett

**Comment by mvaneijgen** [comment]
Hey, Great! Looking good. 

By default `Jekyll` will use the `_config.yml` file to setup everything for your website (that what it uses on `github.io`, but it maybe that your `local` and `dev` have a different structure to it (like it did in the beginning without your `CNAME` file). So with `--config _config.yml,_config-dev-.yml` you say to `Jekyll` I will use `_config.yml`, but overwrite it with all the values in `_config-dev.yml`. If you take a look at `_config-dev.yml` there is only one value there and that is to reset your `baseurl` for local use.

**Comment by palixeb** [comment]
Thanks!

On Fri, Nov 20, 2015 at 4:48 PM, Mitchel van Eijgen <
notifications@github.com> wrote:

> Hey, Great! Looking good.
> 
> By default Jekyll will use the _config.yml file to setup everything for
> your website (that what it uses on github.io, but it maybe that your local
> and dev have a different structure to it (like it did in the beginning
> without your CNAME file). So with --config _config.yml,_config-dev-.yml
> you say to Jekyll I will use _config.yml, but overwrite it with all the
> values in _config-dev.yml. If you take a look at _config-dev.yml there is
> only one value there and that is to reset your baseurl for local use.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/palixeb/palixeb.github.io/issues/3#issuecomment-158313737
> .

## 

Phill Bennett

**Comment by palixeb** [comment]
Take the world's best courses, online. Coursera envisions a world where 
anyone, anywhere can transform their life by accessing the world’s best 
learning experience.
[Ready to learn something new?]
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLlVaTjN1X2NaRWVXVzloTDYwci1hS1EiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDQ1YWIxNmM2ZWZhYjc0MWEzYmY0MDlmYjZiNjc1MWVkYjMyNzcyZWM0OTIwODk5MmNmMDAwMDAwMDExMjY2OTIzYTkyYTE2OWNlMDZlMzNiZmRAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uVVpOM3VfY1pFZVdXOWhMNjByLWFLUSJ9fSwidXNlcklkIjotMX0.GastOdgks_r8VuZA928nyXtUivK6nuRx7LGM4gnL7d0  
My Courses
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLlVaTjN1X2NaRWVXVzloTDYwci1hS1EiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDQ1YWIxNmM2ZWZhYjc0MWEzYmY0MDlmYjZiNjc1MWVkYjMyNzcyZWM0OTIwODk5MmNmMDAwMDAwMDExMjY2OTIzYTkyYTE2OWNlMDZlMzNiZmRAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uVVpOM3VfY1pFZVdXOWhMNjByLWFLUSJ9fSwidXNlcklkIjotMX0.GastOdgks_r8VuZA928nyXtUivK6nuRx7LGM4gnL7d0 
Course Catalog
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvY291cnNlcz91dG1fbWVkaXVtPWVtYWlsJnV0bV9zb3VyY2U9aW52aXRhdGlvbnMmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by5VWk4zdV9jWkVlV1c5aEw2MHItYUtRIiwidHJhY2tpbmciOnsidXNlcklkIjotMSwidXNlckVtYWlsIjoicmVwbHkrMDA0NWFiMTZjNmVmYWI3NDFhM2JmNDA5ZmI2YjY3NTFlZGIzMjc3MmVjNDkyMDg5OTJjZjAwMDAwMDAxMTI2NjkyM2E5MmExNjljZTA2ZTMzYmZkQHJlcGx5LmdpdGh1Yi5jb20iLCJub3RpZmljYXRpb25UeXBlIjoiZ3Jvd3RoLmludml0YXRpb24iLCJjYW1wYWlnbklkIjoibm90aWZpY2F0aW9ucy5hdXRvLlVaTjN1X2NaRWVXVzloTDYwci1hS1EifX0sInVzZXJJZCI6LTF9.U0vQOOZtyzScpX8xqPc1PjXGzgbofn5fYHOL2MtD684

Phill Bennett thinks you'll love learning on Coursera

We envision a world where anyone, anywhere can transform their life by 
accessing the world’s best learning experience. We offer hundreds open 
online courses, in dozens of subject areas, all from top universities and 
institutions.

Course topics range from business and management, to computer science, to 
medicine, music, education, and more.

Millions of our learners have advanced their careers, discovered new 
passions, and built lasting friendships through their Coursera courses. We 
hope you'll join us in learning without limits!

The Coursera Team

Explore Coursera
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvb25ib2FyZGluZy8_dG9rZW49NDJkMjlkODJkNGE2Mzk4ZjhjMDZmOTBkNDVhMTc1MjQmZW1haWw9cmVwbHkrMDA0NWFiMTZjNmVmYWI3NDFhM2JmNDA5ZmI2YjY3NTFlZGIzMjc3MmVjNDkyMDg5OTJjZjAwMDAwMDAxMTI2NjkyM2E5MmExNjljZTA2ZTMzYmZkQHJlcGx5LmdpdGh1Yi5jb20mbmFtZT1wYWxpeGViL3BhbGl4ZWIuZ2l0aHViLmlvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLlVaTjN1X2NaRWVXVzloTDYwci1hS1EiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDQ1YWIxNmM2ZWZhYjc0MWEzYmY0MDlmYjZiNjc1MWVkYjMyNzcyZWM0OTIwODk5MmNmMDAwMDAwMDExMjY2OTIzYTkyYTE2OWNlMDZlMzNiZmRAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uVVpOM3VfY1pFZVdXOWhMNjByLWFLUSJ9fSwidXNlcklkIjotMX0.L0Bm_UmY52XqSlOXWrc1RA0zkmJden4eWsOux9w-s88
Download our App:  iOS
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2l0dW5lcy5hcHBsZS5jb20vYXBwL2FwcGxlLXN0b3JlL2lkNzM2NTM1OTYxP2N0PU1vYmlsZSUyMFByb21vJTIwRW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZtdD04JnB0PTIzMzQxNTAmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by5VWk4zdV9jWkVlV1c5aEw2MHItYUtRJnV0bV9tZWRpdW09ZW1haWwiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDQ1YWIxNmM2ZWZhYjc0MWEzYmY0MDlmYjZiNjc1MWVkYjMyNzcyZWM0OTIwODk5MmNmMDAwMDAwMDExMjY2OTIzYTkyYTE2OWNlMDZlMzNiZmRAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uVVpOM3VfY1pFZVdXOWhMNjByLWFLUSJ9fSwidXNlcklkIjotMX0.ePNWQUw8szgwWUghkYT7bmslV6tspCY2moQ0uSLs1_0 
  |  Android
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3BsYXkuZ29vZ2xlLmNvbS9zdG9yZS9hcHBzL2RldGFpbHM_aWQ9b3JnLmNvdXJzZXJhLmFuZHJvaWQmdXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uVVpOM3VfY1pFZVdXOWhMNjByLWFLUSIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwNDVhYjE2YzZlZmFiNzQxYTNiZjQwOWZiNmI2NzUxZWRiMzI3NzJlYzQ5MjA4OTkyY2YwMDAwMDAwMTEyNjY5MjNhOTJhMTY5Y2UwNmUzM2JmZEByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by5VWk4zdV9jWkVlV1c5aEw2MHItYUtRIn19LCJ1c2VySWQiOi0xfQ.HVqU7wVwSbhNjbg9YmgVS1xVmG-U94_EtsIL9nAIyG4
Learner Help Center
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2xlYXJuZXIuY291cnNlcmEuaGVscC8_dXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uVVpOM3VfY1pFZVdXOWhMNjByLWFLUSIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwNDVhYjE2YzZlZmFiNzQxYTNiZjQwOWZiNmI2NzUxZWRiMzI3NzJlYzQ5MjA4OTkyY2YwMDAwMDAwMTEyNjY5MjNhOTJhMTY5Y2UwNmUzM2JmZEByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by5VWk4zdV9jWkVlV1c5aEw2MHItYUtRIn19LCJ1c2VySWQiOi0xfQ.4IJNqvAf3eeWeORKFi8UyLy6xe5RlleUQkLudgjNoZ4 
  | Please do not reply directly to this email
To no longer receive invitations from your friends on Coursera, 
Unsubscribe
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvYWNjb3VudC91bnN1YnNjcmliZS9FTjl3ZEd4U3l1WDJHdDkwLTNJczJRMDdiWlJSRUdWVVBuaHZkM0lGREg3eXoySEQya0VOSzRrR0pQWUUzSjh4QlFveHFveE9RTEhUVnZpWUxnZnJ4Zy42UHhlc3FTSDhCRVF0S0ptR2VURGR3LjFjajJrREswUDZ1eG14ekx4WUpqOXo0SzFwLV9zMk9BdV92d2FDYzRYak1ZeV9fVnJyRXRZdVRxMXdzSVNuTnU4SlI3eVc3Rm02SFc4akItUWdpMk02NkwtY1cyemVNa1NwY2NYaXZld1NEY0EybXZJWlR0bXNEdmM2TmNBMTRWdHRpMWMwZktVVm5mR1B0X2YydXg0aDJVd1phcTdnTFY4UWZ3YlYxQ0I3OHk1aW9INWExQW9NWmcwYmVCbWx0YmZSaE1FLUlvSXpEb1Z4R3dENlZQZWNLSElJOUw5c3Rpc3dVaU5vbTVybmk3OXdaNTZ0a2pfS0R6d3lhYW1KbE53Rm1WLVEzYTc4MFVXbV9VZkw5cVNXb0RLWWR6ODRzTjgzR0ZobHNDdnFhR0tLM0UxQUg0dXpkVU1CcHJuVjFyP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLlVaTjN1X2NaRWVXVzloTDYwci1hS1EiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDQ1YWIxNmM2ZWZhYjc0MWEzYmY0MDlmYjZiNjc1MWVkYjMyNzcyZWM0OTIwODk5MmNmMDAwMDAwMDExMjY2OTIzYTkyYTE2OWNlMDZlMzNiZmRAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uVVpOM3VfY1pFZVdXOWhMNjByLWFLUSJ9fSwidXNlcklkIjotMX0.tLrYU5wqY5tREGxcEjKpjFe4uZXpCL-aFm-0nm8QjKQ
Copyright © 2016, Coursera Inc. | 381 E. Evelyn Ave, Mountain View, CA 
94041 USA

**Comment by palixeb** [comment]
Take the world's best courses, online. Coursera envisions a world where 
anyone, anywhere can transform their life by accessing the world’s best 
learning experience.
[Ready to learn something new?]
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLlVaUEZOdmNaRWVXZnBRcGRhNjhkTnciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDQ1YWIxNjYxN2FjN2QzZjZmOThlOTMxYzMxNGUwOGJjYjJlOTZjOTYxN2RlMDU5MmNmMDAwMDAwMDExMjU0YjYyZDkyYTE2OWNlMDZlMzNiZmRAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uVVpQRk52Y1pFZVdmcFFwZGE2OGROdyJ9fSwidXNlcklkIjotMX0.J-McxfQUYYxt1uXm9aNd0rKBu5hwtn5_SE8ceAjwjdA  
My Courses
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLlVaUEZOdmNaRWVXZnBRcGRhNjhkTnciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDQ1YWIxNjYxN2FjN2QzZjZmOThlOTMxYzMxNGUwOGJjYjJlOTZjOTYxN2RlMDU5MmNmMDAwMDAwMDExMjU0YjYyZDkyYTE2OWNlMDZlMzNiZmRAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uVVpQRk52Y1pFZVdmcFFwZGE2OGROdyJ9fSwidXNlcklkIjotMX0.J-McxfQUYYxt1uXm9aNd0rKBu5hwtn5_SE8ceAjwjdA 
Course Catalog
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvY291cnNlcz91dG1fbWVkaXVtPWVtYWlsJnV0bV9zb3VyY2U9aW52aXRhdGlvbnMmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by5VWlBGTnZjWkVlV2ZwUXBkYTY4ZE53IiwidHJhY2tpbmciOnsidXNlcklkIjotMSwidXNlckVtYWlsIjoicmVwbHkrMDA0NWFiMTY2MTdhYzdkM2Y2Zjk4ZTkzMWMzMTRlMDhiY2IyZTk2Yzk2MTdkZTA1OTJjZjAwMDAwMDAxMTI1NGI2MmQ5MmExNjljZTA2ZTMzYmZkQHJlcGx5LmdpdGh1Yi5jb20iLCJub3RpZmljYXRpb25UeXBlIjoiZ3Jvd3RoLmludml0YXRpb24iLCJjYW1wYWlnbklkIjoibm90aWZpY2F0aW9ucy5hdXRvLlVaUEZOdmNaRWVXZnBRcGRhNjhkTncifX0sInVzZXJJZCI6LTF9.g5JcoTg6nGUSog-_vtAIH8R9JiyvPez7zfPO5YA87Oo

Phill Bennett thinks you'll love learning on Coursera

We envision a world where anyone, anywhere can transform their life by 
accessing the world’s best learning experience. We offer hundreds open 
online courses, in dozens of subject areas, all from top universities and 
institutions.

Course topics range from business and management, to computer science, to 
medicine, music, education, and more.

Millions of our learners have advanced their careers, discovered new 
passions, and built lasting friendships through their Coursera courses. We 
hope you'll join us in learning without limits!

The Coursera Team

Explore Coursera
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvb25ib2FyZGluZy8_dG9rZW49NTU2ZTBlZmEzNGY4OWJiOTA0OTAyMTEwNGI3MTlmNjImZW1haWw9cmVwbHkrMDA0NWFiMTY2MTdhYzdkM2Y2Zjk4ZTkzMWMzMTRlMDhiY2IyZTk2Yzk2MTdkZTA1OTJjZjAwMDAwMDAxMTI1NGI2MmQ5MmExNjljZTA2ZTMzYmZkQHJlcGx5LmdpdGh1Yi5jb20mbmFtZT1wYWxpeGViL3BhbGl4ZWIuZ2l0aHViLmlvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLlVaUEZOdmNaRWVXZnBRcGRhNjhkTnciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDQ1YWIxNjYxN2FjN2QzZjZmOThlOTMxYzMxNGUwOGJjYjJlOTZjOTYxN2RlMDU5MmNmMDAwMDAwMDExMjU0YjYyZDkyYTE2OWNlMDZlMzNiZmRAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uVVpQRk52Y1pFZVdmcFFwZGE2OGROdyJ9fSwidXNlcklkIjotMX0.1b2mfNI2N568dSyWtwJ2WkgfkSxs4RybW0oNmszHlpY
Download our App:  iOS
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2l0dW5lcy5hcHBsZS5jb20vYXBwL2FwcGxlLXN0b3JlL2lkNzM2NTM1OTYxP2N0PU1vYmlsZSUyMFByb21vJTIwRW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZtdD04JnB0PTIzMzQxNTAmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by5VWlBGTnZjWkVlV2ZwUXBkYTY4ZE53JnV0bV9tZWRpdW09ZW1haWwiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDQ1YWIxNjYxN2FjN2QzZjZmOThlOTMxYzMxNGUwOGJjYjJlOTZjOTYxN2RlMDU5MmNmMDAwMDAwMDExMjU0YjYyZDkyYTE2OWNlMDZlMzNiZmRAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uVVpQRk52Y1pFZVdmcFFwZGE2OGROdyJ9fSwidXNlcklkIjotMX0.wKSjNPAHRcV4dR0AF5KctMGHwBoSE19d0soMc7mLWxc 
  |  Android
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3BsYXkuZ29vZ2xlLmNvbS9zdG9yZS9hcHBzL2RldGFpbHM_aWQ9b3JnLmNvdXJzZXJhLmFuZHJvaWQmdXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uVVpQRk52Y1pFZVdmcFFwZGE2OGROdyIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwNDVhYjE2NjE3YWM3ZDNmNmY5OGU5MzFjMzE0ZTA4YmNiMmU5NmM5NjE3ZGUwNTkyY2YwMDAwMDAwMTEyNTRiNjJkOTJhMTY5Y2UwNmUzM2JmZEByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by5VWlBGTnZjWkVlV2ZwUXBkYTY4ZE53In19LCJ1c2VySWQiOi0xfQ.g9ebCuZZSRYd6sPqVkOvH7clT5GiLj-15fnRBmMgMno
Learner Help Center
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2xlYXJuZXIuY291cnNlcmEuaGVscC8_dXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uVVpQRk52Y1pFZVdmcFFwZGE2OGROdyIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwNDVhYjE2NjE3YWM3ZDNmNmY5OGU5MzFjMzE0ZTA4YmNiMmU5NmM5NjE3ZGUwNTkyY2YwMDAwMDAwMTEyNTRiNjJkOTJhMTY5Y2UwNmUzM2JmZEByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by5VWlBGTnZjWkVlV2ZwUXBkYTY4ZE53In19LCJ1c2VySWQiOi0xfQ.MgvxgJ_D7v9BfvrfPK5qKVhAtK8QGVIZYS75nX41BRY 
  | Please do not reply directly to this email
To no longer receive invitations from your friends on Coursera, 
Unsubscribe
https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvYWNjb3VudC91bnN1YnNjcmliZS9BODh1clJPYmowQUwtdXhpaTdfSWhGdUpsT3JlZ3pJSDRaVVpFUFJmejFlNXJpVjlINW9leFAwMFg3V3pyRkZHYTcwQXlNVzgtc3gzc21FUi1GYlI1dy5KNVdXbVdSWnl3Z2x3a3hFMGlUcjl3Lmw4Y0RLOVdQZXFUcVZyWE9rRmR1NUVjdFp1VXl3a0tLRURORDlZb1FGb0lKa0xCZEQ0Tjhsc2djM0xwUFBTcEZGVXE1Z0MtVEZ5V3RYbFBzSjhiR2QtZFJ6YTRmRTBQQUp1T0NwdXhDWHdsNXl5dk1DTnR5LXQyb0V0dnJ0Q3lIajRlT3FPVjRFLWphdXB6WnJ4c1RNYzRVTE9janpHVG1XZV9kXzdPTlc0bUx4Mm16NDFDYW9JQ3JBaExVNzFKV183YmxKemMwcmtwdDFzcTV5bEJkOV84WXFHYjZQNUJsdmVoS2JOVWtYTS1DWjhzNV95U0s3cnNLd2s1NmN5TFRCTi15QVhlMGhBLUlKTE40YzdDNWREdjBVc2N3WC1ZWjlkNXVvY1phYzQxQjgxWDdvQjJtajlwYW5XOHVSMGtkP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLlVaUEZOdmNaRWVXZnBRcGRhNjhkTnciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDQ1YWIxNjYxN2FjN2QzZjZmOThlOTMxYzMxNGUwOGJjYjJlOTZjOTYxN2RlMDU5MmNmMDAwMDAwMDExMjU0YjYyZDkyYTE2OWNlMDZlMzNiZmRAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uVVpQRk52Y1pFZVdmcFFwZGE2OGROdyJ9fSwidXNlcklkIjotMX0.9ZGzfByWzPyagXvQiXJ9S-5_3yC0b6_B6NBV4ldrFTQ
Copyright © 2016, Coursera Inc. | 381 E. Evelyn Ave, Mountain View, CA 
94041 USA

**Comment by amandabob84** [comment]
Skinners all of you !!
